### ISSUE TITLE
Bank interface drag & drop issues

### ISSUE THREAD

**Issue by vddCore** [Pazaz/RT4-Client#2]
Neither insertion, swapping within nor dropping an item on a bank tab appear to work. The reproduction is included in the video. Item withdrawal from the bank in the beginning of the video is irrelevant.

There are no logs available, as none were provided by the client.

https://user-images.githubusercontent.com/4654533/171101493-d1101c4c-3b68-4ead-98b4-c2acdf205f5c.mp4

**Comment by Pazaz** [comment]
Thanks for the report, and especially the video. I'll take a look at this soon.

**Comment by downthecrop** [comment]
I was researching this. looks like the packet is made here (Line 489):  https://github.com/Pazaz/RT4-Client/blob/master/client/src/main/java/rt4/ClientProt.java#L489

![qYXhGpQLs7](https://user-images.githubusercontent.com/4764745/171545818-d5c7ba6a-cfb6-481b-a497-b38f53b921ad.gif)



Edit:

Additional research

There was a modification made in the legacy client to enable dragging.

legacy-client - Client.java
```
if (Class56.aClass11_886 != null && Class56.aClass11_886 != inter && var26 && (method44(inter).method98() 
        || (inter.componentHash == 49938505 && Class56.aClass11_886.componentHash == 49938505))) {
    Class27.aClass11_526 = inter;
}
```

specifically the deviation is ` || (inter.componentHash == 49938505 && Class56.aClass11_886.componentHash == 49938505)`

This is copying the interface when banking because the server isn't sending a second interface

The equivalent file for RT4 is  https://github.com/Pazaz/RT4-Client/blob/5e66d3ba0110125968c92ee4aba36b18ee73c465/client/src/main/java/rt4/Static36.java#L126


**Solutions**

Get the server to send a second interface to the player for banking to restore functionality instead of doing this hack.

**Comment by Ceikry** [comment]
> I was researching this. looks like the packet is made here (Line 489): https://github.com/Pazaz/RT4-Client/blob/master/client/src/main/java/rt4/ClientProt.java#L489
> 
> ![qYXhGpQLs7](https://user-images.githubusercontent.com/4764745/171545818-d5c7ba6a-cfb6-481b-a497-b38f53b921ad.gif) [ ](https://user-images.githubusercontent.com/4764745/171545818-d5c7ba6a-cfb6-481b-a497-b38f53b921ad.gif) ![qYXhGpQLs7](https://user-images.githubusercontent.com/4764745/171545818-d5c7ba6a-cfb6-481b-a497-b38f53b921ad.gif) [ ](https://user-images.githubusercontent.com/4764745/171545818-d5c7ba6a-cfb6-481b-a497-b38f53b921ad.gif)
> 
> Edit:
> 
> Additional research
> 
> There was a modification made in the legacy client to enable dragging.
> 
> legacy-client - Client.java
> 
> ```
> if (Class56.aClass11_886 != null && Class56.aClass11_886 != inter && var26 && (method44(inter).method98() 
>         || (inter.componentHash == 49938505 && Class56.aClass11_886.componentHash == 49938505))) {
>     Class27.aClass11_526 = inter;
> }
> ```
> 
> specifically the deviation is ` || (inter.componentHash == 49938505 && Class56.aClass11_886.componentHash == 49938505)`
> 
> This is copying the interface when banking because the server isn't sending a second interface
> 
> The equivalent file for RT4 is
> 
> https://github.com/Pazaz/RT4-Client/blob/5e66d3ba0110125968c92ee4aba36b18ee73c465/client/src/main/java/rt4/Static36.java#L126
> 
> **Solutions**
> 
> Get the server to send a second interface to the player for banking to restore functionality instead of doing this hack.

This is incorrect, it is exactly as I said it was about a week ago and no one had to waste their time digging through the client. Simple iface settings.
https://gitlab.com/2009scape/2009scape/-/merge_requests/601

**Comment by Ceikry** [comment]
This issue can be closed

**Comment by Pazaz** [comment]
Thanks, closing. To recap: this was an incorrect server behavior and this (original) client exposed an issue there.
